leftnav:
- identifier: c91b99e7-335b-d2cf-c777-0329588910a2
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: e5cb2f3b-8875-bec8-dbe0-deabef515cbf
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 569b558c-8364-e2c4-7c1d-7ed82dfae2b9
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 5c43c593-8120-feb1-4c3c-128d914d3de9
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: 97933b78-e988-c714-561e-5815ad429a23
  name: Exams
  pageRef: /pages/exams
  weight: 50
- identifier: dd0b944b-2c9a-69c2-c42a-f71a50177f0a
  name: Related Resources
  pageRef: /pages/related-resources
  weight: 60
